// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import multipart "mime/multipart"

// Uploader is an autogenerated mock type for the Uploader type
type Uploader struct {
	mock.Mock
}

// Upload provides a mock function with given fields: fileHeader, file
func (_m *Uploader) Upload(fileHeader *multipart.FileHeader, file multipart.File) (string, error) {
	ret := _m.Called(fileHeader, file)

	var r0 string
	if rf, ok := ret.Get(0).(func(*multipart.FileHeader, multipart.File) string); ok {
		r0 = rf(fileHeader, file)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*multipart.FileHeader, multipart.File) error); ok {
		r1 = rf(fileHeader, file)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
